{
 "title": "系统（详细）",
 "description": "Metric view designed for a single system since some graphs overlay multiple queries.",
 "tags": [
  "prometheus",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(system_uptime, instance)"
    }
   },
   {
    "name": "disk_device",
    "query": {
     "query": "label_values(disk_used_percent{fstype!=\"rootfs\", instance=\"$instance\"}, device)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(net_bytes_sent{instance=\"$instance\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Logged In Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_users{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100-cpu_usage_idle{instance=\"$instance\", cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "CPU Total %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{instance=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "User"
    },
    {
     "expr": "cpu_usage_system{instance=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "System"
    },
    {
     "expr": "cpu_usage_idle{instance=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Cores - User",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{instance=\"$instance\", cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Cores - System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_system{instance=\"$instance\", cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_buffered{instance=\"$instance\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "mem_cached{instance=\"$instance\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "mem_free{instance=\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{instance=\"$instance\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "system_load5{instance=\"$instance\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "system_load15{instance=\"$instance\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "processes_blocked{instance=\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "processes_dead{instance=\"$instance\"}",
     "legendFormat": "Dead"
    },
    {
     "expr": "processes_idle{instance=\"$instance\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "processes_paging{instance=\"$instance\"}",
     "legendFormat": "Paging"
    },
    {
     "expr": "processes_running{instance=\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "processes_sleeping{instance=\"$instance\"}",
     "legendFormat": "Sleeping"
    },
    {
     "expr": "processes_stopped{instance=\"$instance\"}",
     "legendFormat": "Stopped"
    },
    {
     "expr": "processes_unknown{instance=\"$instance\"}",
     "legendFormat": "Unknown"
    },
    {
     "expr": "processes_zombies{instance=\"$instance\"}",
     "legendFormat": "Zombies"
    }
   ]
  },
  {
   "title": "Context Switch & Interrupt Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_context_switches{instance=\"$instance\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "rate(kernel_interrupts{instance=\"$instance\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Docker Run State",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_n_containers_running{instance=\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "docker_n_containers_stopped{instance=\"$instance\"}",
     "legendFormat": "Stopped"
    },
    {
     "expr": "docker_n_containers_paused{instance=\"$instance\"}",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "title": "Disk  Device: $disk_device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "disk_device",
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk used - $disk_device",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk capacity - $disk_device",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_free{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Free on {{path}}"
    },
    {
     "expr": "disk_used{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Used on {{path}}"
    }
   ]
  },
  {
   "title": "Disk IO Time Rate - $disk_device",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_time{instance=\"$instance\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "Read Time"
    },
    {
     "expr": "rate(diskio_write_time{instance=\"$instance\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "Write Time"
    },
    {
     "expr": "rate(diskio_io_time{instance=\"$instance\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "IO Time"
    }
   ]
  },
  {
   "title": "Inodes Free - $disk_device",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 42 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_inodes_free{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "disk_inodes_used{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Inodes - $disk_device",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_inodes_free{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Free on {{path}}"
    },
    {
     "expr": "disk_inodes_used{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\"}",
     "legendFormat": "Used on {{path}}"
    }
   ]
  },
  {
   "title": "Disk IO Bytes Rate - $disk_device",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{instance=\"$instance\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(diskio_write_bytes{instance=\"$instance\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  {
   "title": "Network Interface: $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 },
   "repeat": "interface",
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Bytes Rate - $interface",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "Sent {{interface}}"
    },
    {
     "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "Received {{interface}}"
    }
   ]
  },
  {
   "title": "Network Packets Rate - $interface",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "Sent {{interface}}"
    },
    {
     "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "Received {{interface}}"
    }
   ]
  },
  {
   "title": "Errors In Total - $interface",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Errors Out Total - $interface",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network Error & Drop Rate - $interface",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 214 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "error_in"
    },
    {
     "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "error_out"
    },
    {
     "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "drop_in"
    },
    {
     "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}[5m])",
     "legendFormat": "drop_out"
    }
   ]
  },
  {
   "title": "Drop In Total - $interface",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Drop Out Total - $interface",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$instance\"}"
    }
   ]
  }
 ]
}