route:
  group_by: ["alertname"] 
  group_wait: 10s 
  group_interval: 10s 
  repeat_interval: 15m 
  receiver: default

receivers:
  - name: "default"
    webhook_configs:
      - url: "http://127.0.0.1/alertmanager/webhook"
